<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Carbon\Carbon;
class CreateTableVehiculos extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('vehiculos', function (Blueprint $table) {
            $table->id();
            $table->string('tipo_vehiculo_id');
            $table->float('m3_desde', 6, 2);
            $table->float('m3_hasta', 6, 2);
            $table->string('carga_util');
            $table->integer('num_plazas');
            $table->integer('num_puertas');
            $table->string('cambio');
            $table->boolean('aire_acondicionado');
            $table->float('largo_vehiculo', 6, 2);
            $table->float('alto_vehiculo', 6, 2);
            $table->float('ancho_vehiculo', 6, 2);
            $table->float('largo_carga_vehiculo', 6, 2);
            $table->float('alto_carga_vehiculo', 6, 2);
            $table->float('ancho_carga_vehiculo', 6, 2);
            $table->integer('edad_minima_conductor');
            $table->integer('antiguedad_carnet');
            $table->float('franquicia_reserva', 6, 2);
            $table->string('politica_combustible');
            $table->string('imagen_exterior');
            $table->string('imagen_interior');
            $table->string('imagen_carga');
            $table->longText('descripcion');
            $table->timestamps();
            $table->softDeletes();

            $table->foreign('tipo_vehiculo_id')->references('tipo_vehiculo_id')->on('tipos_vehiculo');
        });

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'DERTUR2',
            'm3_desde'              => '0',
            'm3_hasta'              => '3',
            'carga_util'            => '750 Kg.',
            'num_plazas'            => '2',
            'cambio'                => 'Manual',
            'num_puertas'           => '3',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.40',
            'alto_vehiculo'         => '1.86',
            'ancho_vehiculo'        => '1.75',
            'largo_carga_vehiculo'  => '1.60',
            'alto_carga_vehiculo'   => '1.25',
            'ancho_carga_vehiculo'  => '1.45',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler ideal para transportar personas (modelo combi) o cargas ligeras (modelo comercial) con un volumen de carga de entre 2-3 m³, lo que te permitirá un transporte bajo en consumo, fácil manejo en accesos difíciles y rapidez.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURPEQ',
            'm3_desde'              => '6',
            'm3_hasta'              => '8',
            'carga_util'            => '925 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.10',
            'alto_vehiculo'         => '1.90',
            'ancho_vehiculo'        => '1.92',
            'largo_carga_vehiculo'  => '2.60',
            'alto_carga_vehiculo'   => '1.40',
            'ancho_carga_vehiculo'  => '1.70',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler con espacio de carga aproximado entre 6 - 8 m³ ideal para transportar cargas donde no necesitemos una gran altura en el espacio de carga pero ganando en profundidad o longitud, por lo que podremos incorporar cargas más voluminosas que puedan ser transportadas preferiblemente de forma horizontal en el espacio de carga.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURMED',
            'm3_desde'              => '8',
            'm3_hasta'              => '10',
            'carga_util'            => '945 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.98',
            'alto_vehiculo'         => '2.35',
            'ancho_vehiculo'        => '2.04',
            'largo_carga_vehiculo'  => '3.30',
            'alto_carga_vehiculo'   => '1.70',
            'ancho_carga_vehiculo'  => '1.70',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler con espacio de carga aproximado entre 8 - 10 m³ ideal para transportar cargas que requieran una mayor altura, siendo la profundidad o longitud del espacio de carga similar al del segmento pequeño. Ganamos volumen de carga gracias a una mayor altura.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURGRA',
            'm3_desde'              => '10',
            'm3_hasta'              => '12',
            'carga_util'            => '1.280 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.92',
            'alto_vehiculo'         => '2.60',
            'ancho_vehiculo'        => '2.00',
            'largo_carga_vehiculo'  => '3.30',
            'alto_carga_vehiculo'   => '1.93',
            'ancho_carga_vehiculo'  => '1.75',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler con espacio de carga aproximado entre 10 - 12 m³ ideal para transportar cargas  voluminosas como pequeñas mudanzas o transporte de mercancías altas. Ganamos altura, anchura y profundidad o longitud en el espacio de carga. Es la furgoneta más utilizada en el transporte de cargas con volúmenes considerables. ',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FUREXTGRA',
            'm3_desde'              => '12',
            'm3_hasta'              => '15',
            'carga_util'            => '1.360 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.00',
            'alto_vehiculo'         => '2.52',
            'ancho_vehiculo'        => '2.05',
            'largo_carga_vehiculo'  => '3.60',
            'alto_carga_vehiculo'   => '2.10',
            'ancho_carga_vehiculo'  => '1.75',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler con espacio de carga aproximado entre 12 - 15 m³ ideal para transportar cargas voluminosas que requieran un espacio de carga con mayor longitud o profundidad que el segmento grande. Es el alquiler perfecto para esas cargas donde se nos queda pequeña una furgoneta grande pero no queremos/necesitamos el alquiler de camiones. ',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'CARSINPLA16',
            'm3_desde'              => '1',
            'm3_hasta'              => '16',
            'carga_util'            => '850 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.50',
            'alto_vehiculo'         => '3.00',
            'ancho_vehiculo'        => '2.20',
            'largo_carga_vehiculo'  => '4.00',
            'alto_carga_vehiculo'   => '2.00',
            'ancho_carga_vehiculo'  => '2.00',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Pequeño camión de alquiler con espacio de carga aproximado de 16 m³ ideal para transportar grandes cargas de amplios volúmenes como grandes mudanzas, piezas de gran longitud, material de gran altura o simplemente cargas con multitud de unidades. Es el vehículo referencia para el transporte en mudanzas o variedad de mobiliario. Permitida su circulación con el carnet de conducir "B", es decir, el que llamamos el carnet del coche.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'CARCONPLA16',
            'm3_desde'              => '1',
            'm3_hasta'              => '16',
            'carga_util'            => '500 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.50',
            'alto_vehiculo'         => '3.00',
            'ancho_vehiculo'        => '2.20',
            'largo_carga_vehiculo'  => '4.00',
            'alto_carga_vehiculo'   => '2.00',
            'ancho_carga_vehiculo'  => '2.00',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Pequeño camión de alquiler con espacio de carga aproximado de 16 m³ ideal para transportar grandes cargas de amplios volúmenes y peso donde requiramos de una plataforma elevadora para subir la carga al vehículo como grandes mudanzas, piezas de construcción, maquinaria pesada, etc... Es el vehículo referencia para el transporte en mudanzas o variedad de mobiliario. Permitida su circulación con el carnet de conducir "B", es decir, el que llamamos el carnet del coche.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURMIX',
            'm3_desde'              => '1',
            'm3_hasta'              => '4',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '6',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.30',
            'alto_vehiculo'         => '1.94',
            'ancho_vehiculo'        => '1.92',
            'largo_carga_vehiculo'  => '1.72',
            'alto_carga_vehiculo'   => '1.32',
            'ancho_carga_vehiculo'  => '1.60',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler ideal para transportar hasta 6 personas donde además necesitamos un volumen de carga considerable, en este caso comprendido entre 3 - 4 m³. Tendremos ese espacio de carga suficiente para amplios volúmenes de equipaje, material para eventos y resto de cargas voluminosas.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FUR9P',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '9',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.55',
            'alto_vehiculo'         => '2.48',
            'ancho_vehiculo'        => '2.07',
            'largo_carga_vehiculo'  => '1.45',
            'alto_carga_vehiculo'   => '1.87',
            'ancho_carga_vehiculo'  => '1.76',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler para transportar hasta 9 personas, es el vehículo referencia para viajes de ocio, turismos, eventos multitudinarios, etc... Nos ofrece numerosas comodidades para disfrutar de viajes donde los kilómetros se pasen "volando". Disfruta de la altura ideal para poder aparcar en parking subterráneos del centro de ciudades ampliamente transitadas. Asientos totalmente plegables e independientes que nos permite configurar la distribución de asientos a nuestro gusto y donde nadie discutirá por la posición de su asiento.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'MON',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '9',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.34',
            'alto_vehiculo'         => '1.97',
            'ancho_vehiculo'        => '2.03',
            'largo_carga_vehiculo'  => '1.05',
            'alto_carga_vehiculo'   => '1.30',
            'ancho_carga_vehiculo'  => '1.55',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler para transportar hasta 9 personas, es el vehículo referencia para viajes de ocio, turismos, eventos multitudinarios, etc... Nos ofrece numerosas comodidades para disfrutar de viajes donde los kilómetros se pasen "volando". Disfruta de la altura ideal para poder aparcar en parking subterráneos del centro de ciudades ampliamente transitadas. Asientos totalmente plegables e independientes que nos permite configurar la distribución de asientos a nuestro gusto y donde nadie discutirá por la posición de su asiento.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'TURPEQ',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '300 l.',
            'num_plazas'            => '5',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '3.97',
            'alto_vehiculo'         => '1.50',
            'ancho_vehiculo'        => '1.72',
            'largo_carga_vehiculo'  => '0',
            'alto_carga_vehiculo'   => '0',
            'ancho_carga_vehiculo'  => '0',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Turismo de último modelo ligero y pequeño, con hasta 5 plazas para pasajeros. Bajo consumo, alta manejabilidad y facilidad de aparcamiento.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'TURMED',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '385 l.',
            'num_plazas'            => '5',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.38',
            'alto_vehiculo'         => '1.50',
            'ancho_vehiculo'        => '1.72',
            'largo_carga_vehiculo'  => '0',
            'alto_carga_vehiculo'   => '0',
            'ancho_carga_vehiculo'  => '0',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Turismo del segmento medio, equipado con toda la tecnología de los últimos modelos del mercado. Nos permite transportar hasta 5 personas con comodidad y buenas prestaciones de motor. Mayor capacidad de carga destinada al equipaje.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURADA',
            'm3_desde'              => '0',
            'm3_hasta'              => '4',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '6',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.55',
            'alto_vehiculo'         => '2.48',
            'ancho_vehiculo'        => '2.07',
            'largo_carga_vehiculo'  => '0',
            'alto_carga_vehiculo'   => '0',
            'ancho_carga_vehiculo'  => '0',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta adaptada para el transporte de persona con movilidad reducida, nos permite combinar varias plazas para pasajeros y sillas de ruedas. Este vehículo adaptado también incorpora otros accesorios para facilitrar el acceso a personas con dificultades de movilidad, contando con todos los sistemas de seguridad pertinentes.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURGISOMED',
            'm3_desde'              => '0',
            'm3_hasta'              => '11',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '3',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.98',
            'alto_vehiculo'         => '2.35',
            'ancho_vehiculo'        => '2.04',
            'largo_carga_vehiculo'  => '2.75',
            'alto_carga_vehiculo'   => '1.75',
            'ancho_carga_vehiculo'  => '1.75',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta carrozada con espacio de carga isotérmico y equipada con un equipo de frío que te permitirá regular la temperatura a la que quieres que se trasnporte tu mercancía. Perfecta para transportar esos alimentos que necesitan conservarse en frío o regularizar su temperatura. Espacio de carga de mayor volumen próximo a los 10 - 12 m³.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'MONEXE',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '9',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.34',
            'alto_vehiculo'         => '1.97',
            'ancho_vehiculo'        => '2.03',
            'largo_carga_vehiculo'  => '1.05',
            'alto_carga_vehiculo'   => '1.30',
            'ancho_carga_vehiculo'  => '1.55',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler "premium" para transportar hasta 9 personas, con todo tipo de comodidades y acabados de lujo. Es el vehículo referencia para viajes de ocio, turismos, eventos multitudinarios, etc... Nos ofrece numerosas comodidades para disfrutar de viajes donde los kilómetros se pasen "volando". Disfruta de la altura ideal para poder aparcar en parking subterráneos del centro de ciudades ampliamente transitadas. Asientos totalmente plegables e independientes que nos permite configurar la distribución de asientos a nuestro gusto y donde nadie discutirá por la posición de su asiento.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'CARISO',
            'm3_desde'              => '0',
            'm3_hasta'              => '16',
            'carga_util'            => '700 Kg.',
            'num_plazas'            => '2',
            'cambio'                => 'Manual',
            'num_puertas'           => '3',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.85',
            'alto_vehiculo'         => '3.10',
            'ancho_vehiculo'        => '2.20',
            'largo_carga_vehiculo'  => '4.15',
            'alto_carga_vehiculo'   => '1.90',
            'ancho_carga_vehiculo'  => '2.00',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Pequeño camión equipado con espacio de carga isotérmico y un equipo de frío para regular la temperatura del interior del espacio de carga. Destinado para el transporte de grandes volúmenes de mercancías que requieren de una temperatura determinada, la cual podrás programar de manera sencilla y rápida. Dispone de un espacio de carga comprendido entre los 16-18 m³.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'TTMED',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '375 l.',
            'num_plazas'            => '5',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.18',
            'alto_vehiculo'         => '1.61',
            'ancho_vehiculo'        => '1.78',
            'largo_carga_vehiculo'  => '0',
            'alto_carga_vehiculo'   => '0',
            'ancho_carga_vehiculo'  => '0',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Todoterreno Mediano, también conocido como "Todocamino" o "SUV" perfecto para la conducción urbana en ciudades, carreteras y terrenos algo más inestables. Su conducción es similar a la de un turismo pero ganamos en altura,espacio para pasajeros y capacidad de maletero. Su consumo es reducido, similar a la de un turismo, lo que hace una opción perfectas para cualquier tipo de viaje.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'TTGRAN',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '430 l.',
            'num_plazas'            => '5',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.40',
            'alto_vehiculo'         => '1.59',
            'ancho_vehiculo'        => '1.81',
            'largo_carga_vehiculo'  => '0',
            'alto_carga_vehiculo'   => '0',
            'ancho_carga_vehiculo'  => '0',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Todoterreno Grande, también conocido como "Todocamino" o "SUV" perfecto para la conducción urbana en ciudades, carreteras y terrenos algo más inestables. El espacio destinado a pasajeros es amplio, la capacidad del maletero amplia para albergar sin problema la carga de sus 5 plazas de pasajeros y tenemos ganamos en altura para una mejor visión en la conducción. El espacio en conjunto de este vehículo es algo superior al Todoterreno Mediano que encontramos en flota.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'MON7',
            'm3_desde'              => '0',
            'm3_hasta'              => '0',
            'carga_util'            => '152 - 710 l.',
            'num_plazas'            => '5',
            'cambio'                => 'Manual',
            'num_puertas'           => '5',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.66',
            'alto_vehiculo'         => '1.68',
            'ancho_vehiculo'        => '1.88',
            'largo_carga_vehiculo'  => '0',
            'alto_carga_vehiculo'   => '0',
            'ancho_carga_vehiculo'  => '0',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta monovolumen de alquiler donde podrían viajar hasta 7 personas, obtenemos la flexibilidad de elegir y optimizar el espacio en función de nuestras necesidades gracias a su dos asientos traseros, los cuáles se pueden abatir sin problemas para ganar espacio de carga. Nos ofrece dos alternativas a la hora de viajar; en caso de transportar menos personas podemos ampliar el espacio de carga hasta los 710 litros de capacidad, mientras que si por el contrario necesitásemos transportar hasta 7 personas, el espacio de carga se reduciría hasta 152 litros de capacidad. Con esta flexibilidad podemos jugar hasta un punto intermedio en el que el monovolumen pueda transportar hasta 6 personas y el espacio de carga se optimice a lo que realmente necesitemos. Otra ventaja de nuestra magnífico monovolumen de 7 plazas es que se conduce igual que un turismo y tendrá los mismos límites de velocidad que estos, evitando así tener que optar a otros segmentos que están limitados al ser considerados vehículos industriales. Por supuesto, no se nos puede pasar mencionaros que cuentan con todo tipo de extras que os harán el viaje mucho más ameno, cómodo y eficiente gracias a la última tecnología en navegación y entretenimiento del mercado.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURGISOPEQ',
            'm3_desde'              => '0',
            'm3_hasta'              => '1.90',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '2',
            'cambio'                => 'Manual',
            'num_puertas'           => '3',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.40',
            'alto_vehiculo'         => '1.86',
            'ancho_vehiculo'        => '1.75',
            'largo_carga_vehiculo'  => '1.30',
            'alto_carga_vehiculo'   => '1.50',
            'ancho_carga_vehiculo'  => '1.40',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta carrozada con espacio de carga isotérmico, ideal para el transporte de alimentos y otras materias primas perecedera, este tipo de vehículo te permitirá conservar la temperatura de manera estable en tu espacio de carga. Tamaño de carga reducido para mercancias de volumenes reducidos, en torno a los 5-8 m³.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'DERTURCOMBI',
            'm3_desde'              => '0',
            'm3_hasta'              => '3',
            'carga_util'            => '750 kg.',
            'num_plazas'            => '5',
            'cambio'                => 'Manual',
            'num_puertas'           => '3',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.40',
            'alto_vehiculo'         => '1.86',
            'ancho_vehiculo'        => '1.75',
            'largo_carga_vehiculo'  => '1.60',
            'alto_carga_vehiculo'   => '1.25',
            'ancho_carga_vehiculo'  => '1.45',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler ideal para transportar personas (modelo combi) o cargas ligeras (modelo comercial) con un volumen de carga de entre 2-3 m³, lo que te permitirá un transporte bajo en consumo, fácil manejo en accesos difíciles y rapidez.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURGISOMP',
            'm3_desde'              => '6',
            'm3_hasta'              => '8',
            'carga_util'            => '0 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '3',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.98',
            'alto_vehiculo'         => '2.35',
            'ancho_vehiculo'        => '2.04',
            'largo_carga_vehiculo'  => '2.65',
            'alto_carga_vehiculo'   => '1.70',
            'ancho_carga_vehiculo'  => '1.75',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta carrozada con espacio de carga isotérmico, ideal para el transporte de alimentos y otras materias primas perecedera, este tipo de vehículo te permitirá conservar la temperatura de manera estable en tu espacio de carga. Tamaño de carga reducido para mercancias de volumenes reducidos, en torno a los 10-12 m³.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'DERTUR1',
            'm3_desde'              => '0',
            'm3_hasta'              => '4',
            'carga_util'            => '750 Kg.',
            'num_plazas'            => '2',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '4.60',
            'alto_vehiculo'         => '1.86',
            'ancho_vehiculo'        => '1.75',
            'largo_carga_vehiculo'  => '1.95',
            'alto_carga_vehiculo'   => '1.30',
            'ancho_carga_vehiculo'  => '1.54',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler ideal para transportar personas (modelo combi) o cargas ligeras (modelo comercial) con un volumen de carga de entre 2,5 - 3,5 m³, lo que te permitirá un transporte bajo en consumo, fácil manejo en accesos difíciles y rapidez. ',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'CSP+',
            'm3_desde'              => '0',
            'm3_hasta'              => '20',
            'carga_util'            => '850 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.85',
            'alto_vehiculo'         => '3.10',
            'ancho_vehiculo'        => '2.20',
            'largo_carga_vehiculo'  => '4.30',
            'alto_carga_vehiculo'   => '2.10',
            'ancho_carga_vehiculo'  => '2.00',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Pequeño camión de alquiler con espacio de carga aproximado entre 18 - 20 m³ ideal para transportar grandes cargas de amplios volúmenes como grandes mudanzas, piezas de gran longitud, material de gran altura o simplemente cargas con multitud de unidades. Es el vehículo referencia para el transporte en mudanzas o variedad de mobiliario. Permitida su circulación con el carnet de conducir "B", es decir, el que llamamos el carnet del coche.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'CARCONPLA',
            'm3_desde'              => '0',
            'm3_hasta'              => '20',
            'carga_util'            => '500 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.85',
            'alto_vehiculo'         => '3.10',
            'ancho_vehiculo'        => '2.20',
            'largo_carga_vehiculo'  => '4.30',
            'alto_carga_vehiculo'   => '2.10',
            'ancho_carga_vehiculo'  => '2.00',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Pequeño camión de alquiler con espacio de carga aproximado entre 18 - 20 m³ ideal para transportar grandes cargas de amplios volúmenes y peso donde requiramos de una plataforma elevadora para subir la carga al vehículo como grandes mudanzas, piezas de construcción, maquinaria pesada, etc... Es el vehículo referencia para el transporte en mudanzas o variedad de mobiliario. Permitida su circulación con el carnet de conducir "B", es decir, el que llamamos el carnet del coche.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FURMIX+',
            'm3_desde'              => '0',
            'm3_hasta'              => '5',
            'carga_util'            => '1.100 Kg.',
            'num_plazas'            => '6',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '5.30',
            'alto_vehiculo'         => '2.37',
            'ancho_vehiculo'        => '2.03',
            'largo_carga_vehiculo'  => '1.90',
            'alto_carga_vehiculo'   => '1.75',
            'ancho_carga_vehiculo'  => '1.70',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler ideal para transportar hasta 6 personas donde además necesitamos un volumen de carga considerable, en este caso comprendido entre 4 - 5 m³ y a diferencia de la furgoneta mixta simple, en este caso dispondremos de una mayor altura en el espacio de carga y por tanto un mayor volumen de carga. Esta furgoneta también cuenta con le ventaja de que está categorizada como turismo lo que no nos limitará la velocdiad a 90 en autovía, sino que se aplican los límites de velocidad normales de coches turismos.',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

        DB::table('vehiculos')->insert([
            'tipo_vehiculo_id'      => 'FUREXTGRA+',
            'm3_desde'              => '12',
            'm3_hasta'              => '15',
            'carga_util'            => '1.360 Kg.',
            'num_plazas'            => '3',
            'cambio'                => 'Manual',
            'num_puertas'           => '4',
            'aire_acondicionado'    => '1',
            'largo_vehiculo'        => '6.00',
            'alto_vehiculo'         => '2.52',
            'ancho_vehiculo'        => '2.05',
            'largo_carga_vehiculo'  => '3.60',
            'alto_carga_vehiculo'   => '2.10',
            'ancho_carga_vehiculo'  => '1.75',
            'edad_minima_conductor' => '23',
            'antiguedad_carnet'     => '2',
            'franquicia_reserva'    => '600',
            'politica_combustible'  => 'Lleno / Lleno',
            'imagen_exterior'       => '',
            'imagen_interior'       => '',
            'imagen_carga'          => '',
            'descripcion'           => 'Furgoneta de alquiler con espacio de carga aproximado entre 14 - 16 m³, similar a la furgoneta extra grande del grupo (E) pero en este caso contaremos con una longitud de carga mayor, al ser de batalla extra larga. Estos nos permitirá transportar cargas de mayor longitud de hasta cerca de 4 metros sin tener que recurrir a camiones de alquiler, contando por tanto, con un consumo más reducido de combustible y una mayor comodidad en la conducción. Idónea para pequeñas mudanzas o transporte de bultos largos como vigas, estructuras metálicas, monopostes, etc...',
            'created_at'            => Carbon::now(),
            'updated_at'            => Carbon::now(),
        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('vehiculos', function (Blueprint $table) {
            $table->dropForeign('vehiculos_tipo_vehiculo_id_foreign');
        });

        Schema::dropIfExists('vehiculos');
    }
}
